{
 "title": "Order Service Overview",
 "tags": [
  "orders",
  "observability-lab"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Request rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"order-service\"}[1m]))",
     "legendFormat": "all"
    },
    {
     "expr": "sum(rate(http_requests_total{job=\"order-service\",status=~\"5..\"}[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Error rate %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"order-service\",status=~\"5..\"}[5m])) / clamp_min(sum(rate(http_requests_total{job=\"order-service\"}[5m])), 1e-9) * 100",
     "legendFormat": "5xx %"
    }
   ]
  },
  {
   "title": "Latency p50 / p95 / p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{job=\"order-service\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"order-service\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=\"order-service\"}[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Orders created / failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(orders_created_total[1m])) by (payment_method)",
     "legendFormat": "created {{payment_method}}"
    },
    {
     "expr": "sum(rate(orders_failed_total[1m])) by (reason)",
     "legendFormat": "failed {{reason}}"
    }
   ]
  },
  {
   "title": "Chaos knobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "chaos_fail_rate", "legendFormat": "fail_rate" },
    { "expr": "chaos_latency_ms", "legendFormat": "latency_ms" }
   ]
  },
  {
   "title": "Recent app logs (Loki)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{service=\"order-service\"} |= ``"
    }
   ]
  }
 ]
}